development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: alex
 pool: 5
 username: root
 password: Barca@123
 socket: /var/run/mysqld/mysqld.sock
 
test:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: alex
 pool: 5
 username: root
 password: Barca@123
 socket: /var/run/mysqld/mysqld.sock
 
production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: alex
 pool: 5
 username: root
 password: Barca@123
 socket: /var/run/mysqld/mysqld.sock
